name: check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
        working-directory: ./server
      - run: npm run lint
        working-directory: ./server
  test:
    needs: [lint]
    strategy:
      matrix:
        version: [16, 18, 20]
        os: [ubuntu-latest, windows-latest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - run: npm ci
        working-directory: ./server
      - run: npm run --workspaces test
        working-directory: ./server
